export interface CountryConfig {
    code: string;
    name: string;
    locale: string;
    currency: string;
}

export const countries: CountryConfig[] = [
    { code: "AF", name: "Afghanistan", locale: "fa-AF", currency: "AFN" },
    { code: "AX", name: "Åland Islands", locale: "sv-AX", currency: "EUR" },
    { code: "AL", name: "Albania", locale: "sq-AL", currency: "ALL" },
    { code: "DZ", name: "Algeria", locale: "ar-DZ", currency: "DZD" },
    { code: "AS", name: "American Samoa", locale: "en-AS", currency: "USD" },
    { code: "AD", name: "Andorra", locale: "ca-AD", currency: "EUR" },
    { code: "AO", name: "Angola", locale: "pt-AO", currency: "AOA" },
    { code: "AI", name: "Anguilla", locale: "en-AI", currency: "XCD" },
    { code: "AQ", name: "Antarctica", locale: "en-AQ", currency: "XXX" },
    { code: "AG", name: "Antigua & Barbuda", locale: "en-AG", currency: "XCD" },
    { code: "AR", name: "Argentina", locale: "es-AR", currency: "ARS" },
    { code: "AM", name: "Armenia", locale: "hy-AM", currency: "AMD" },
    { code: "AW", name: "Aruba", locale: "nl-AW", currency: "AWG" },
    { code: "AC", name: "Ascension Island", locale: "en-AC", currency: "SHP" },
    { code: "AU", name: "Australia", locale: "en-AU", currency: "AUD" },
    { code: "AT", name: "Austria", locale: "de-AT", currency: "EUR" },
    { code: "AZ", name: "Azerbaijan", locale: "az-AZ", currency: "AZN" },

    { code: "BS", name: "Bahamas", locale: "en-BS", currency: "BSD" },
    { code: "BH", name: "Bahrain", locale: "ar-BH", currency: "BHD" },
    { code: "BD", name: "Bangladesh", locale: "bn-BD", currency: "BDT" },
    { code: "BB", name: "Barbados", locale: "en-BB", currency: "BBD" },
    { code: "BY", name: "Belarus", locale: "be-BY", currency: "BYN" },
    { code: "BE", name: "Belgium", locale: "nl-BE", currency: "EUR" },
    { code: "BZ", name: "Belize", locale: "en-BZ", currency: "BZD" },
    { code: "BJ", name: "Benin", locale: "fr-BJ", currency: "XOF" },
    { code: "BM", name: "Bermuda", locale: "en-BM", currency: "BMD" },
    { code: "BT", name: "Bhutan", locale: "dz-BT", currency: "BTN" },
    { code: "BO", name: "Bolivia", locale: "es-BO", currency: "BOB" },
    { code: "BA", name: "Bosnia & Herzegovina", locale: "bs-BA", currency: "BAM" },
    { code: "BW", name: "Botswana", locale: "en-BW", currency: "BWP" },
    { code: "BV", name: "Bouvet Island", locale: "no-BV", currency: "NOK" },
    { code: "BR", name: "Brazil", locale: "pt-BR", currency: "BRL" },
    { code: "IO", name: "British Indian Ocean Territory", locale: "en-IO", currency: "USD" },
    { code: "VG", name: "British Virgin Islands", locale: "en-VG", currency: "USD" },
    { code: "BN", name: "Brunei", locale: "ms-BN", currency: "BND" },
    { code: "BG", name: "Bulgaria", locale: "bg-BG", currency: "EUR" },
    { code: "BF", name: "Burkina Faso", locale: "fr-BF", currency: "XOF" },
    { code: "BI", name: "Burundi", locale: "fr-BI", currency: "BIF" },

    { code: "CV", name: "Cape Verde", locale: "pt-CV", currency: "CVE" },
    { code: "KH", name: "Cambodia", locale: "km-KH", currency: "KHR" },
    { code: "CM", name: "Cameroon", locale: "fr-CM", currency: "XAF" },
    { code: "CA", name: "Canada", locale: "en-CA", currency: "CAD" },
    { code: "KY", name: "Cayman Islands", locale: "en-KY", currency: "KYD" },
    { code: "CF", name: "Central African Republic", locale: "fr-CF", currency: "XAF" },
    { code: "TD", name: "Chad", locale: "fr-TD", currency: "XAF" },
    { code: "CL", name: "Chile", locale: "es-CL", currency: "CLP" },
    { code: "CN", name: "China", locale: "zh-CN", currency: "CNY" },
    { code: "CX", name: "Christmas Island", locale: "en-CX", currency: "AUD" },
    { code: "CC", name: "Cocos (Keeling) Islands", locale: "en-CC", currency: "AUD" },
    { code: "CO", name: "Colombia", locale: "es-CO", currency: "COP" },
    { code: "KM", name: "Comoros", locale: "ar-KM", currency: "KMF" },
    { code: "CG", name: "Congo - Brazzaville", locale: "fr-CG", currency: "XAF" },
    { code: "CD", name: "Congo - Kinshasa", locale: "fr-CD", currency: "CDF" },
    { code: "CK", name: "Cook Islands", locale: "en-CK", currency: "NZD" },
    { code: "CR", name: "Costa Rica", locale: "es-CR", currency: "CRC" },
    { code: "CI", name: "Côte d’Ivoire", locale: "fr-CI", currency: "XOF" },
    { code: "HR", name: "Croatia", locale: "hr-HR", currency: "EUR" },
    { code: "CU", name: "Cuba", locale: "es-CU", currency: "CUP" },
    { code: "CW", name: "Curaçao", locale: "nl-CW", currency: "XCG" },
    { code: "CY", name: "Cyprus", locale: "el-CY", currency: "EUR" },
    { code: "CZ", name: "Czechia", locale: "cs-CZ", currency: "CZK" },

    { code: "DK", name: "Denmark", locale: "da-DK", currency: "DKK" },
    { code: "DJ", name: "Djibouti", locale: "fr-DJ", currency: "DJF" },
    { code: "DM", name: "Dominica", locale: "en-DM", currency: "XCD" },
    { code: "DO", name: "Dominican Republic", locale: "es-DO", currency: "DOP" },

    { code: "EC", name: "Ecuador", locale: "es-EC", currency: "USD" },
    { code: "EG", name: "Egypt", locale: "ar-EG", currency: "EGP" },
    { code: "SV", name: "El Salvador", locale: "es-SV", currency: "USD" },
    { code: "GQ", name: "Equatorial Guinea", locale: "es-GQ", currency: "XAF" },
    { code: "ER", name: "Eritrea", locale: "ti-ER", currency: "ERN" },
    { code: "EE", name: "Estonia", locale: "et-EE", currency: "EUR" },
    { code: "SZ", name: "Eswatini", locale: "en-SZ", currency: "SZL" },
    { code: "ET", name: "Ethiopia", locale: "am-ET", currency: "ETB" },

    { code: "FK", name: "Falkland Islands", locale: "en-FK", currency: "FKP" },
    { code: "FO", name: "Faroe Islands", locale: "fo-FO", currency: "DKK" },
    { code: "FJ", name: "Fiji", locale: "en-FJ", currency: "FJD" },
    { code: "FI", name: "Finland", locale: "fi-FI", currency: "EUR" },
    { code: "FR", name: "France", locale: "fr-FR", currency: "EUR" },
    { code: "GF", name: "French Guiana", locale: "fr-GF", currency: "EUR" },
    { code: "PF", name: "French Polynesia", locale: "fr-PF", currency: "XPF" },
    { code: "TF", name: "French Southern Territories", locale: "fr-TF", currency: "EUR" },

    { code: "GA", name: "Gabon", locale: "fr-GA", currency: "XOF" },
    { code: "GM", name: "Gambia", locale: "en-GM", currency: "GMD" },
    { code: "GE", name: "Georgia", locale: "ka-GE", currency: "GEL" },
    { code: "DE", name: "Germany", locale: "de-DE", currency: "EUR" },
    { code: "GH", name: "Ghana", locale: "en-GH", currency: "GHS" },
    { code: "GI", name: "Gibraltar", locale: "en-GI", currency: "GIP" },
    { code: "GR", name: "Greece", locale: "el-GR", currency: "EUR" },
    { code: "GL", name: "Greenland", locale: "kl-GL", currency: "DKK" },
    { code: "GD", name: "Grenada", locale: "en-GD", currency: "XCD" },
    { code: "GP", name: "Guadeloupe", locale: "fr-GP", currency: "EUR" },
    { code: "GU", name: "Guam", locale: "en-GU", currency: "USD" },
    { code: "GT", name: "Guatemala", locale: "es-GT", currency: "GTQ" },
    { code: "GG", name: "Guernsey", locale: "en-GG", currency: "GBP" },
    { code: "GN", name: "Guinea", locale: "fr-GN", currency: "GNF" },
    { code: "GW", name: "Guinea-Bissau", locale: "pt-GW", currency: "XOF" },
    { code: "GY", name: "Guyana", locale: "en-GY", currency: "GYD" },

    { code: "HT", name: "Haiti", locale: "fr-HT", currency: "HTG" },
    { code: "HM", name: "Heard & McDonald Islands", locale: "en-HM", currency: "AUD" },
    { code: "HN", name: "Honduras", locale: "es-HN", currency: "HNL" },
    { code: "HK", name: "Hong Kong", locale: "zh-Hant-HK", currency: "HKD" },
    { code: "HU", name: "Hungary", locale: "hu-HU", currency: "HUF" },

    { code: "IS", name: "Iceland", locale: "is-IS", currency: "ISK" },
    { code: "IN", name: "India", locale: "en-IN", currency: "INR" },
    { code: "ID", name: "Indonesia", locale: "id-ID", currency: "IDR" },
    { code: "IR", name: "Iran", locale: "fa-IR", currency: "IRR" },
    { code: "IQ", name: "Iraq", locale: "ar-IQ", currency: "IQD" },
    { code: "IE", name: "Ireland", locale: "en-IE", currency: "EUR" },
    { code: "IM", name: "Isle of Man", locale: "en-IM", currency: "GBP" },
    { code: "IL", name: "Israel", locale: "he-IL", currency: "ILS" },
    { code: "IT", name: "Italy", locale: "it-IT", currency: "EUR" },

    { code: "JM", name: "Jamaica", locale: "en-JM", currency: "JMD" },
    { code: "JP", name: "Japan", locale: "ja-JP", currency: "JPY" },
    { code: "JE", name: "Jersey", locale: "en-JE", currency: "GBP" },
    { code: "JO", name: "Jordan", locale: "ar-JO", currency: "JOD" },

    { code: "KZ", name: "Kazakhstan", locale: "kk-KZ", currency: "KZT" },
    { code: "KE", name: "Kenya", locale: "sw-KE", currency: "KES" },
    { code: "KI", name: "Kiribati", locale: "en-KI", currency: "AUD" },
    { code: "KP", name: "North Korea", locale: "ko-KP", currency: "KPW" },
    { code: "KR", name: "South Korea", locale: "ko-KR", currency: "KRW" },
    { code: "KW", name: "Kuwait", locale: "ar-KW", currency: "KWD" },
    { code: "KG", name: "Kyrgyzstan", locale: "ky-KG", currency: "KGS" },

    { code: "LA", name: "Laos", locale: "lo-LA", currency: "LAK" },
    { code: "LV", name: "Latvia", locale: "lv-LV", currency: "EUR" },
    { code: "LB", name: "Lebanon", locale: "ar-LB", currency: "LBP" },
    { code: "LS", name: "Lesotho", locale: "en-LS", currency: "LSL" },
    { code: "LR", name: "Liberia", locale: "en-LR", currency: "LRD" },
    { code: "LY", name: "Libya", locale: "ar-LY", currency: "LYD" },
    { code: "LI", name: "Liechtenstein", locale: "de-LI", currency: "CHF" },
    { code: "LT", name: "Lithuania", locale: "lt-LT", currency: "EUR" },
    { code: "LU", name: "Luxembourg", locale: "lb-LU", currency: "EUR" },

    { code: "MO", name: "Macao", locale: "zh-Hant-MO", currency: "MOP" },
    { code: "MG", name: "Madagascar", locale: "mg-MG", currency: "MGA" },
    { code: "MW", name: "Malawi", locale: "en-MW", currency: "MWK" },
    { code: "MY", name: "Malaysia", locale: "ms-MY", currency: "MYR" },
    { code: "MV", name: "Maldives", locale: "dv-MV", currency: "MVR" },
    { code: "ML", name: "Mali", locale: "fr-ML", currency: "XOF" },
    { code: "MT", name: "Malta", locale: "mt-MT", currency: "EUR" },
    { code: "MH", name: "Marshall Islands", locale: "en-MH", currency: "USD" },
    { code: "MQ", name: "Martinique", locale: "fr-MQ", currency: "EUR" },
    { code: "MR", name: "Mauritania", locale: "ar-MR", currency: "MRU" },
    { code: "MU", name: "Mauritius", locale: "en-MU", currency: "MUR" },
    { code: "YT", name: "Mayotte", locale: "fr-YT", currency: "EUR" },
    { code: "MX", name: "Mexico", locale: "es-MX", currency: "MXN" },
    { code: "FM", name: "Micronesia", locale: "en-FM", currency: "USD" },
    { code: "MD", name: "Moldova", locale: "ro-MD", currency: "MDL" },
    { code: "MC", name: "Monaco", locale: "fr-MC", currency: "EUR" },
    { code: "MN", name: "Mongolia", locale: "mn-MN", currency: "MNT" },
    { code: "ME", name: "Montenegro", locale: "sr-ME", currency: "EUR" },
    { code: "MS", name: "Montserrat", locale: "en-MS", currency: "XCD" },
    { code: "MA", name: "Morocco", locale: "ar-MA", currency: "MAD" },
    { code: "MZ", name: "Mozambique", locale: "pt-MZ", currency: "MZN" },
    { code: "MM", name: "Myanmar", locale: "my-MM", currency: "MMK" },

    { code: "NA", name: "Namibia", locale: "en-NA", currency: "NAD" },
    { code: "NR", name: "Nauru", locale: "en-NR", currency: "AUD" },
    { code: "NP", name: "Nepal", locale: "ne-NP", currency: "NPR" },
    { code: "NL", name: "Netherlands", locale: "nl-NL", currency: "EUR" },
    { code: "NC", name: "New Caledonia", locale: "fr-NC", currency: "XPF" },
    { code: "NZ", name: "New Zealand", locale: "en-NZ", currency: "NZD" },
    { code: "NI", name: "Nicaragua", locale: "es-NI", currency: "NIO" },
    { code: "NE", name: "Niger", locale: "fr-NE", currency: "XOF" },
    { code: "NG", name: "Nigeria", locale: "en-NG", currency: "NGN" },
    { code: "NU", name: "Niue", locale: "en-NU", currency: "NZD" },
    { code: "NF", name: "Norfolk Island", locale: "en-NF", currency: "AUD" },
    { code: "MK", name: "North Macedonia", locale: "mk-MK", currency: "MKD" },
    { code: "MP", name: "Northern Mariana Islands", locale: "en-MP", currency: "USD" },
    { code: "NO", name: "Norway", locale: "nb-NO", currency: "NOK" },

    { code: "OM", name: "Oman", locale: "ar-OM", currency: "OMR" },

    { code: "PK", name: "Pakistan", locale: "en-PK", currency: "PKR" },
    { code: "PW", name: "Palau", locale: "en-PW", currency: "USD" },
    { code: "PS", name: "Palestinian Territories", locale: "ar-PS", currency: "ILS" },
    { code: "PA", name: "Panama", locale: "es-PA", currency: "PAB" },
    { code: "PG", name: "Papua New Guinea", locale: "en-PG", currency: "PGK" },
    { code: "PY", name: "Paraguay", locale: "es-PY", currency: "PYG" },
    { code: "PE", name: "Peru", locale: "es-PE", currency: "PEN" },
    { code: "PH", name: "Philippines", locale: "en-PH", currency: "PHP" },
    { code: "PN", name: "Pitcairn", locale: "en-PN", currency: "NZD" },
    { code: "PL", name: "Poland", locale: "pl-PL", currency: "PLN" },
    { code: "PT", name: "Portugal", locale: "pt-PT", currency: "EUR" },
    { code: "PR", name: "Puerto Rico", locale: "es-PR", currency: "USD" },

    { code: "QA", name: "Qatar", locale: "ar-QA", currency: "QAR" },

    { code: "RE", name: "Réunion", locale: "fr-RE", currency: "EUR" },
    { code: "RO", name: "Romania", locale: "ro-RO", currency: "RON" },
    { code: "RU", name: "Russia", locale: "ru-RU", currency: "RUB" },
    { code: "RW", name: "Rwanda", locale: "rw-RW", currency: "RWF" },

    { code: "BL", name: "St. Barthélemy", locale: "fr-BL", currency: "EUR" },
    { code: "SH", name: "St. Helena", locale: "en-SH", currency: "SHP" },
    { code: "KN", name: "St. Kitts & Nevis", locale: "en-KN", currency: "XCD" },
    { code: "LC", name: "St. Lucia", locale: "en-LC", currency: "XCD" },
    { code: "MF", name: "St. Martin", locale: "fr-MF", currency: "EUR" },
    { code: "PM", name: "St. Pierre & Miquelon", locale: "fr-PM", currency: "EUR" },
    { code: "VC", name: "St. Vincent & Grenadines", locale: "en-VC", currency: "XCD" },
    { code: "WS", name: "Samoa", locale: "en-WS", currency: "WST" },
    { code: "SM", name: "San Marino", locale: "it-SM", currency: "EUR" },
    { code: "ST", name: "São Tomé & Príncipe", locale: "pt-ST", currency: "STN" },
    { code: "SA", name: "Saudi Arabia", locale: "ar-SA", currency: "SAR" },
    { code: "SN", name: "Senegal", locale: "fr-SN", currency: "XOF" },
    { code: "RS", name: "Serbia", locale: "sr-RS", currency: "RSD" },
    { code: "SC", name: "Seychelles", locale: "en-SC", currency: "SCR" },
    { code: "SL", name: "Sierra Leone", locale: "en-SL", currency: "SLE" },
    { code: "SG", name: "Singapore", locale: "en-SG", currency: "SGD" },
    { code: "SX", name: "Sint Maarten", locale: "nl-SX", currency: "XCG" },
    { code: "SK", name: "Slovakia", locale: "sk-SK", currency: "EUR" },
    { code: "SI", name: "Slovenia", locale: "sl-SI", currency: "EUR" },
    { code: "SB", name: "Solomon Islands", locale: "en-SB", currency: "SBD" },
    { code: "SO", name: "Somalia", locale: "so-SO", currency: "SOS" },
    { code: "ZA", name: "South Africa", locale: "en-ZA", currency: "ZAR" },
    { code: "GS", name: "South Georgia & South Sandwich Islands", locale: "en-GS", currency: "GBP" },
    { code: "SS", name: "South Sudan", locale: "en-SS", currency: "SSP" },
    { code: "ES", name: "Spain", locale: "es-ES", currency: "EUR" },
    { code: "LK", name: "Sri Lanka", locale: "si-LK", currency: "LKR" },
    { code: "SD", name: "Sudan", locale: "ar-SD", currency: "SDG" },
    { code: "SR", name: "Suriname", locale: "nl-SR", currency: "SRD" },
    { code: "SJ", name: "Svalbard & Jan Mayen", locale: "nb-SJ", currency: "NOK" },
    { code: "SE", name: "Sweden", locale: "sv-SE", currency: "SEK" },
    { code: "CH", name: "Switzerland", locale: "de-CH", currency: "CHF" },
    { code: "SY", name: "Syria", locale: "ar-SY", currency: "SYP" },

    { code: "TW", name: "Taiwan", locale: "zh-TW", currency: "TWD" },
    { code: "TJ", name: "Tajikistan", locale: "tg-TJ", currency: "TJS" },
    { code: "TZ", name: "Tanzania", locale: "sw-TZ", currency: "TZS" },
    { code: "TH", name: "Thailand", locale: "th-TH", currency: "THB" },
    { code: "TL", name: "Timor-Leste", locale: "pt-TL", currency: "USD" },
    { code: "TG", name: "Togo", locale: "fr-TG", currency: "XOF" },
    { code: "TK", name: "Tokelau", locale: "en-TK", currency: "NZD" },
    { code: "TO", name: "Tonga", locale: "to-TO", currency: "TOP" },
    { code: "TT", name: "Trinidad & Tobago", locale: "en-TT", currency: "TTD" },
    { code: "TA", name: "Tristan da Cunha", locale: "en-TA", currency: "GBP" },
    { code: "TN", name: "Tunisia", locale: "ar-TN", currency: "TND" },
    { code: "TR", name: "Türkiye", locale: "tr-TR", currency: "TRY" },
    { code: "TM", name: "Turkmenistan", locale: "tk-TM", currency: "TMT" },
    { code: "TC", name: "Turks & Caicos Islands", locale: "en-TC", currency: "USD" },
    { code: "TV", name: "Tuvalu", locale: "en-TV", currency: "AUD" },

    { code: "UG", name: "Uganda", locale: "en-UG", currency: "UGX" },
    { code: "UA", name: "Ukraine", locale: "uk-UA", currency: "UAH" },
    { code: "AE", name: "United Arab Emirates", locale: "ar-AE", currency: "AED" },
    { code: "GB", name: "United Kingdom", locale: "en-GB", currency: "GBP" },
    { code: "US", name: "United States", locale: "en-US", currency: "USD" },
    { code: "UM", name: "U.S. Outlying Islands", locale: "en-UM", currency: "USD" },
    { code: "UY", name: "Uruguay", locale: "es-UY", currency: "UYU" },
    { code: "UZ", name: "Uzbekistan", locale: "uz-UZ", currency: "UZS" },

    { code: "VU", name: "Vanuatu", locale: "en-VU", currency: "VUV" },
    { code: "VA", name: "Vatican City", locale: "it-VA", currency: "EUR" },
    { code: "VE", name: "Venezuela", locale: "es-VE", currency: "VES" },
    { code: "VN", name: "Vietnam", locale: "vi-VN", currency: "VND" },
    { code: "VI", name: "U.S. Virgin Islands", locale: "en-VI", currency: "USD" },

    { code: "WF", name: "Wallis & Futuna", locale: "fr-WF", currency: "XPF" },
    { code: "EH", name: "Western Sahara", locale: "ar-EH", currency: "MAD" },
    { code: "YE", name: "Yemen", locale: "ar-YE", currency: "YER" },
    { code: "ZM", name: "Zambia", locale: "en-ZM", currency: "ZMW" },
    { code: "ZW", name: "Zimbabwe", locale: "en-ZW", currency: "ZWG" },
];